export const SET_PLACES = 'SET_PLACES'
export const DELETE_PLACE = 'DELETE_PLACE'

export const UI_START_LOADING = 'UI_START_LOADING'
export const UI_STOP_LOADING = 'UI_STOP_LOADING'

export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN'
export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT'